jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant permission to Gradle
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build

  android-tests:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Run emulator and tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  appium-tests:
    runs-on: macos-13
    needs: build
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Run Appium tests
        run: ./gradlew appium-tests:test
